# -*- coding: utf-8 -*-
"""data_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGC1FdrBWZl16lqAWfqZoZCVUoh1DXiC
"""

!pip install kagglehub pandas scikit-learn

import kagglehub

# Download the StockTwits dataset
path = kagglehub.dataset_download("frankcaoyun/stocktwits-2020-2022-raw")

print("Dataset files are in:", path)

import os

print(os.listdir(path))

import pandas as pd
import os
import zipfile
import glob

# Step 1: point to the main dataset folder
data_folder = os.path.join(path, "StockTwits_2020_2022_Raw")

# Step 2: recursively find all CSV and ZIP files
files = glob.glob(os.path.join(data_folder, "**", "*"), recursive=True)

dataframes = []

# Step 3: Load EVERY file
for f in files:
    if f.endswith(".zip"):
        with zipfile.ZipFile(f, 'r') as z:
            for filename in z.namelist():
                if filename.endswith(".csv"):
                    with z.open(filename) as csv_file:
                        df = pd.read_csv(csv_file)
                        dataframes.append(df)
                        print(f"Loaded {filename}")
    elif f.endswith(".csv"):
        df = pd.read_csv(f)
        dataframes.append(df)
        print(f"Loaded {f}")

# Step 4: combine EVERY loaded file
if dataframes:
    combined_df = pd.concat(dataframes, ignore_index=True)
    print("--- FULL DATASET LOADED ---")
    print("Final Combined shape:", combined_df.shape)

combined_df['username'] = combined_df['user'].apply(lambda x: eval(x)['username'] if isinstance(x, str) else x.get('username'))

user_counts = combined_df['username'].value_counts()
print("--- TOP POSTERS (Potential Bots) ---")
print(user_counts.head(10))

# Find exact duplicate messages
duplicate_messages = combined_df['body'].duplicated().sum()
print(f"\nExact Duplicate Messages: {duplicate_messages}")

# Check how many rows have 'None' for sentiment
def check_sentiment(x):
    if isinstance(x, str):
        return 'None' in x
    return False

missing_sentiment = combined_df['entities'].apply(check_sentiment).sum()
print(f"Messages with missing/None sentiment: {missing_sentiment}")
print(f"Percentage of low-quality (unlabeled) data: {(missing_sentiment/len(combined_df))*100:.2f}%")

# Extract Username and Sentiment into their own clean columns
combined_df['username'] = combined_df['user'].apply(lambda x: eval(x)['username'] if isinstance(x, str) else x.get('username'))

def extract_sentiment(x):
    if isinstance(x, str):
        if "'basic': 'Bullish'" in x: return 'Bullish'
        if "'basic': 'Bearish'" in x: return 'Bearish'
    return 'Neutral/None'

combined_df['sentiment_clean'] = combined_df['entities'].apply(extract_sentiment)

# Clean up the date
combined_df['date'] = pd.to_datetime(combined_df['created_at']).dt.date

print("Cleaned columns created: 'username', 'sentiment_clean', and 'date'.")
combined_df[['username', 'sentiment_clean', 'date', 'body']].head()

# Find users who post the same message over and over (Spam)
spam_counts = combined_df.groupby(['username', 'body']).size().reset_index(name='post_count')
spammers = spam_counts[spam_counts['post_count'] > 2]

print(f"Detected {len(spammers)} instances of repetitive spam.")

# Mark these rows as 'Low Quality'
combined_df['is_low_quality'] = combined_df.duplicated(subset=['username', 'body'], keep=False)

print("Quality Check Complete: 'is_low_quality' column added to dataset.")

# Create a dataset that removes the absolute garbage
clean_df = combined_df[combined_df['is_low_quality'] == False].copy()

# Filter for JUST Apple (AAPL) to keep the file size manageable
aapl_clean = clean_df[clean_df['body'].str.contains('AAPL', na=False, case=False)]


aapl_clean.to_csv('AAPL_Cleaned_Sentiment.csv', index=False)
print(f"Cleaned Apple dataset created with {len(aapl_clean)} rows.")

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.move('AAPL_Cleaned_Sentiment.csv', '/content/drive/My Drive/AAPL_Cleaned_Sentiment.csv')
print("File saved to your Google Drive!")