# -*- coding: utf-8 -*-
"""neural_network_train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrRn3hDLlt3Co2cp8HxOuuRyrJVQbkbQ
"""

# Imports
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Embedding, GlobalAveragePooling1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score



# Load cleaned dataset

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/AAPL_Cleaned_Sentiment.csv', low_memory=False)

print(df.shape)
df.head()


# Keep only labeled data

labeled_df = df[df['sentiment_clean'] != 'Neutral/None'].copy()

# Convert labels to numbers
labeled_df['target'] = labeled_df['sentiment_clean'].map({
    'Bullish': 1,
    'Bearish': 0
})

print("Training data size:", labeled_df.shape)


#Convert text to numbers
max_words = 10000
max_len = 50

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(labeled_df['body'])

sequences = tokenizer.texts_to_sequences(labeled_df['body'])
X = pad_sequences(sequences, maxlen=max_len)

y = labeled_df['target'].values

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Data prepared for training")

# Build Neural Network
model = Sequential([
    Embedding(max_words, 16),
    GlobalAveragePooling1D(),
    Dense(16, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# Train model
print("Starting training...")
model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=32,
    validation_data=(X_test, y_test)
)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"\nModel Accuracy: {accuracy:.4f}")

# Predict missing sentiment
missing_df = df[df['sentiment_clean'] == 'Neutral/None'].copy()

print("Missing rows:", len(missing_df))

if len(missing_df) > 0:
    sequences_missing = tokenizer.texts_to_sequences(missing_df['body'])
    X_missing = pad_sequences(sequences_missing, maxlen=max_len)

    preds = model.predict(X_missing)

    # Convert probabilities to labels
    missing_df['predicted_sentiment'] = np.where(preds > 0.5, 'Bullish', 'Bearish')

    print("Sample predictions:")
    print(missing_df[['body', 'predicted_sentiment']].head())

# Save model
model.save('aapl_nn_model.keras')
print("Model saved as aapl_nn_model.keras")


# Save updated dataset
if len(missing_df) > 0:
    df.loc[missing_df.index, 'sentiment_clean'] = missing_df['predicted_sentiment']
    df.to_csv('AAPL_Final_With_Predictions.csv', index=False)
    print("Final dataset saved as AAPL_Final_With_Predictions.csv")